# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DESForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DESForm(object):
    def setupUi(self, DESForm):
        DESForm.setObjectName("DESForm")
        DESForm.setEnabled(True)
        DESForm.resize(752, 516)
        DESForm.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(DESForm)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tblResult = QtWidgets.QTableWidget(self.centralwidget)
        self.tblResult.setEnabled(True)
        self.tblResult.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblResult.setAlternatingRowColors(True)
        self.tblResult.setRowCount(0)
        self.tblResult.setObjectName("tblResult")
        self.tblResult.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tblResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblResult.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tblResult, 0, 1, 1, 1)
        self.vlButtons = QtWidgets.QVBoxLayout()
        self.vlButtons.setObjectName("vlButtons")
        self.btnEncrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnEncrypt.setObjectName("btnEncrypt")
        self.vlButtons.addWidget(self.btnEncrypt)
        self.btnDecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnDecrypt.setObjectName("btnDecrypt")
        self.vlButtons.addWidget(self.btnDecrypt)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vlButtons.addItem(spacerItem)
        self.gridLayout.addLayout(self.vlButtons, 0, 0, 1, 1)
        DESForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DESForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 21))
        self.menubar.setObjectName("menubar")
        DESForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DESForm)
        self.statusbar.setObjectName("statusbar")
        DESForm.setStatusBar(self.statusbar)

        self.retranslateUi(DESForm)
        QtCore.QMetaObject.connectSlotsByName(DESForm)
        DESForm.setTabOrder(self.btnEncrypt, self.btnDecrypt)
        DESForm.setTabOrder(self.btnDecrypt, self.tblResult)

    def retranslateUi(self, DESForm):
        _translate = QtCore.QCoreApplication.translate
        DESForm.setWindowTitle(_translate("DESForm", "DES Encoder"))
        item = self.tblResult.horizontalHeaderItem(0)
        item.setText(_translate("DESForm", "File"))
        item = self.tblResult.horizontalHeaderItem(1)
        item.setText(_translate("DESForm", "Action"))
        item = self.tblResult.horizontalHeaderItem(2)
        item.setText(_translate("DESForm", "Status"))
        item = self.tblResult.horizontalHeaderItem(3)
        item.setText(_translate("DESForm", "Date"))
        self.btnEncrypt.setText(_translate("DESForm", "Encrypt File..."))
        self.btnDecrypt.setText(_translate("DESForm", "Decrypt File..."))
