# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KeyModeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeyModeForm(object):
    def setupUi(self, KeyModeForm):
        KeyModeForm.setObjectName("KeyModeForm")
        KeyModeForm.resize(271, 103)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KeyModeForm.sizePolicy().hasHeightForWidth())
        KeyModeForm.setSizePolicy(sizePolicy)
        KeyModeForm.setMinimumSize(QtCore.QSize(0, 103))
        KeyModeForm.setMaximumSize(QtCore.QSize(16777215, 103))
        self.gridLayout = QtWidgets.QGridLayout(KeyModeForm)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblKey = QtWidgets.QLabel(KeyModeForm)
        self.lblKey.setObjectName("lblKey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblKey)
        self.leKey = QtWidgets.QLineEdit(KeyModeForm)
        self.leKey.setInputMask("")
        self.leKey.setText("")
        self.leKey.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leKey.setObjectName("leKey")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leKey)
        self.lblMode = QtWidgets.QLabel(KeyModeForm)
        self.lblMode.setObjectName("lblMode")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblMode)
        self.cbMode = QtWidgets.QComboBox(KeyModeForm)
        self.cbMode.setObjectName("cbMode")
        self.cbMode.addItem("")
        self.cbMode.addItem("")
        self.cbMode.addItem("")
        self.cbMode.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbMode)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOK = QtWidgets.QPushButton(KeyModeForm)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)

        self.retranslateUi(KeyModeForm)
        QtCore.QMetaObject.connectSlotsByName(KeyModeForm)

    def retranslateUi(self, KeyModeForm):
        _translate = QtCore.QCoreApplication.translate
        KeyModeForm.setWindowTitle(_translate("KeyModeForm", "Key and Mode"))
        self.lblKey.setText(_translate("KeyModeForm", "Key"))
        self.lblMode.setText(_translate("KeyModeForm", "Mode"))
        self.cbMode.setItemText(0, _translate("KeyModeForm", "ECB"))
        self.cbMode.setItemText(1, _translate("KeyModeForm", "CBC"))
        self.cbMode.setItemText(2, _translate("KeyModeForm", "CFB"))
        self.cbMode.setItemText(3, _translate("KeyModeForm", "OFB"))
        self.btnOK.setText(_translate("KeyModeForm", "OK"))
